### ISSUE TITLE
Problem running all the tests

### ISSUE THREAD

**Issue by leosouliotis** [harishravip/python-intermediate-inflammation#5]
It seems that when I try to run to run the tests included using the `pytest` library I get errors that that there is no mule called inflammation.

Any ideas? I am running the command `pytest tests/test_views.py ` from the upper level of this repo.

**Comment by isabelle-gaffney** [comment]
Hi @leosouliotis, did you run `pip install -e .` first?

**Comment by leosouliotis** [comment]
Hi @isabelle-gaffney, I did yes, and got the following error:

```
(venv) [kpvv542@seskscpn084 python-intermediate-inflammation]$ pip install -e .
Obtaining file:///home/kpvv542/test_projects/hrish_soft/python-intermediate-inflammation
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
ERROR: Package 'inflammation' requires a different Python: 3.6.8 not in '<4.0,>=3.8'
```

**Comment by isabelle-gaffney** [comment]
Oh I see! We'll look into it, thanks! :)

**Comment by ghost** [comment]
I am not getting any error, after cloning and then running:
`$ python3 -m venv venv`
`$ source venv/bin/activate`
`$ python3 -m pip install -r requirements.txt`
`$ python3 -m pip install -e .`
`$ pytest tests/test_views.py`

Maybe did the error come from the python version? See in message above:
`ERROR: Package 'inflammation' requires a different Python: 3.6.8 not in '<4.0,>=3.8`
